groups: []

resources:
- name: repo
  type: git
  source:
    uri: {{app-url}}
    branch: {{app-branch}}
    private_key: {{github-private-key}}

- name: m2
  type: docker-image
  source:
    repository: malston/spring-pipeline-m2

- name: version
  type: semver
  source:
    initial_version: 0.0.1
    driver: git
    uri: {{app-url}}
    branch: version
    file: version
    private_key: {{github-private-key}}

jobs:
- name: build-and-upload-snapshot
  plan:
  - aggregate:
    - get: repo
    - get: m2
    - get: version
  - task: build-and-upload
    file: repo/ci/tasks/build-and-upload.yml
    params:
      - _JAVA_OPTIONS: -Djava.security.egd=file:/dev/./urandom
      - M2_SETTINGS_REPO_ID: {{m2-settings-repo-id}}
      - M2_SETTINGS_REPO_USERNAME: {{m2-settings-repo-username}}
      - M2_SETTINGS_REPO_PASSWORD: {{m2-settings-repo-password}}
      - REPO_WITH_JARS: {{snapshot-repo-with-jars}}
      - M2_REPO: {{maven-local-dir}}
      - SNAPSHOT: true
  - aggregate:
    - put: repo
      params:
        repository: out
        tag: out/tag
        only_tag: true
    - put: version
      params: {bump: patch}

- name: build-and-upload-release
  plan:
  - aggregate:
    - get: repo
    - get: m2
    - get: version
  - task: build-and-upload
    file: repo/ci/tasks/build-and-upload.yml
    params:
      - _JAVA_OPTIONS: -Djava.security.egd=file:/dev/./urandom
      - M2_SETTINGS_REPO_ID: {{m2-settings-repo-id}}
      - M2_SETTINGS_REPO_USERNAME: {{m2-settings-repo-username}}
      - M2_SETTINGS_REPO_PASSWORD: {{m2-settings-repo-password}}
      - REPO_WITH_JARS: {{release-repo-with-jars}}
      - M2_REPO: {{maven-local-dir}}
      - SNAPSHOT: false
  - aggregate:
    - put: repo
      params:
        repository: out
        tag: out/tag
        only_tag: true
    - put: version
      params: {bump: patch}
